### ISSUE TITLE
Class'n'ID shortand

### ISSUE THREAD

**Issue by cshaa** [OscarGodson/HTML6#11]
When i was writing an page, I got an idea. Probably it's not good for HTML, I just wanted to know your "humble opinion" :D

My idea is following:
If you think about it, class and id aren't normal attributes. There can't be two elements with equal id value. And css is in fact parsed as an array of attributes, not a single string attr. So why do do this:
`<b id="bold1" class="mark foo">quz</b>`
If you can do this:
`<b#bold1.mark.foo>quz</b>`

It is really close to CSS.
P.S.: Maybe it looks strange when it is plain text but with some syntax highlight, it will be better.
P.P.S.: Or we can implement only a shortand for id.

**Comment by OscarGodson** [comment]
It's cool, but it's not backwards compatible at all. Tags don't allow special characters so browsers would have to do a ton of work to get this to work correctly. In the meantime your code wouldn't fall back either while browsers were upgraded. There'd be no way to select this with CSS and CSS would also have to add support. It's neat, but take a lot of work.

**Comment by cshaa** [comment]
Nothing of HTML6 is back compatibile. It's only a question of importing new DOM parser, everything else will work the same old way. If you don't like it because of difficulty of importing, I can tell you it's not difficult :)
But when I think about it, the class deffinitions are ugly. But that id syntax could be only a shortand for id attribute - the element will parse as if it had id="..." attr. Not much work to implement, huh?

**Comment by OscarGodson** [comment]
Yes :)

Simple example:

``` xml
<foo id="test" class="test"></foo>
<html:foo id="test" class="test"></foo>
<foo id="test" class="test">
```

With JS or CSS you can interact with those elements fine. Notice how GitHub event colors them correctly. Browser still renders the text inside those elements fine and, basically, these work just like any other HTML tag.

``` xml
<b#bold1.mark.foo foo="bar">quz</b>
```

Not will all code highlighters fail (editors, web ones like this, etc), but browsers wont know what to do with it, Have you tried opening something like this in Chrome?

``` html
<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8 />
<title>JS Bin</title>
</head>
<body>
  <b test="test">hkj</b>
  <a#bold1.mark.foo test="test">quz</b>

 <script>
  console.log(document.querySelector('[test]')); // Only returns 1
 </script>
</body>
</html>
```

You would need to write a shim to _all_ of the DOM JS APIs because, to JS, that element doesn't even exist. You'd have to get the body innerHTML and parse it manually. Of course it could be done, but you would have to write a parser before you could use this whereas HTML6 now CSS and JS works fine and writing a shim just means converting a few tags to other tags, but you get all the other stuff free.

**Comment by cshaa** [comment]
Ok, let's close this discussion.
